[package]
name = "wgpu-segfault"
version = "0.1.0"
authors = ["Aaron Hill <aa1ronham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu-core = { path = "/home/aaron/repos/wgpu/wgpu-core" }
wgpu-types = { path = "/home/aaron/repos/wgpu/wgpu-types" } 
